import XCTest

extension ContextTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ContextTests = [
        ("testContextRestoration", testContextRestoration),
        ("testContextSubscripting", testContextSubscripting),
    ]
}

extension EnvironmentBaseAndChildTemplateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EnvironmentBaseAndChildTemplateTests = [
        ("testRuntimeErrorInBaseTemplate", testRuntimeErrorInBaseTemplate),
        ("testRuntimeErrorInChildTemplate", testRuntimeErrorInChildTemplate),
        ("testSyntaxErrorInBaseTemplate", testSyntaxErrorInBaseTemplate),
        ("testSyntaxErrorInChildTemplate", testSyntaxErrorInChildTemplate),
    ]
}

extension EnvironmentIncludeTemplateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EnvironmentIncludeTemplateTests = [
        ("testRuntimeError", testRuntimeError),
        ("testSyntaxError", testSyntaxError),
    ]
}

extension EnvironmentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EnvironmentTests = [
        ("testLoading", testLoading),
        ("testRendering", testRendering),
        ("testRenderingError", testRenderingError),
        ("testSyntaxError", testSyntaxError),
        ("testUnknownFilter", testUnknownFilter),
    ]
}

extension ExpressionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExpressionsTests = [
        ("testAndExpression", testAndExpression),
        ("testEqualityExpression", testEqualityExpression),
        ("testExpressionParsing", testExpressionParsing),
        ("testFalseExpressions", testFalseExpressions),
        ("testFalseInExpression", testFalseInExpression),
        ("testInequalityExpression", testInequalityExpression),
        ("testLessThanEqualExpression", testLessThanEqualExpression),
        ("testLessThanExpression", testLessThanExpression),
        ("testMoreThanEqualExpression", testMoreThanEqualExpression),
        ("testMoreThanExpression", testMoreThanExpression),
        ("testMultipleExpressions", testMultipleExpressions),
        ("testNotExpression", testNotExpression),
        ("testOrExpression", testOrExpression),
        ("testTrueExpressions", testTrueExpressions),
        ("testTrueInExpression", testTrueInExpression),
    ]
}

extension FilterTagTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FilterTagTests = [
        ("testFilterTag", testFilterTag),
    ]
}

extension FilterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FilterTests = [
        ("testDefaultFilter", testDefaultFilter),
        ("testDynamicFilters", testDynamicFilters),
        ("testFilterSuggestion", testFilterSuggestion),
        ("testIndentContent", testIndentContent),
        ("testIndentFirstLine", testIndentFirstLine),
        ("testIndentNotEmptyLines", testIndentNotEmptyLines),
        ("testIndentWithArbitraryCharacter", testIndentWithArbitraryCharacter),
        ("testJoinFilter", testJoinFilter),
        ("testRegistration", testRegistration),
        ("testRegistrationOverrideDefault", testRegistrationOverrideDefault),
        ("testRegistrationWithArguments", testRegistrationWithArguments),
        ("testSplitFilter", testSplitFilter),
        ("testStringFilters", testStringFilters),
        ("testStringFiltersWithArrays", testStringFiltersWithArrays),
    ]
}

extension ForNodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ForNodeTests = [
        ("testArrayOfTuples", testArrayOfTuples),
        ("testForNode", testForNode),
        ("testHandleInvalidInput", testHandleInvalidInput),
        ("testIterateDictionary", testIterateDictionary),
        ("testIterateRange", testIterateRange),
        ("testIterateUsingMirroring", testIterateUsingMirroring),
        ("testLoopMetadata", testLoopMetadata),
        ("testWhereExpression", testWhereExpression),
    ]
}

extension IfNodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IfNodeTests = [
        ("testEvaluatesNilAsFalse", testEvaluatesNilAsFalse),
        ("testParseIf", testParseIf),
        ("testParseIfnot", testParseIfnot),
        ("testParseIfWithElif", testParseIfWithElif),
        ("testParseIfWithElifWithoutElse", testParseIfWithElifWithoutElse),
        ("testParseIfWithElse", testParseIfWithElse),
        ("testParseMultipleElif", testParseMultipleElif),
        ("testParsingErrors", testParsingErrors),
        ("testRendering", testRendering),
        ("testSupportsRangeVariables", testSupportsRangeVariables),
        ("testSupportVariableFilters", testSupportVariableFilters),
    ]
}

extension IncludeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__IncludeTests = [
        ("testParsing", testParsing),
        ("testRendering", testRendering),
    ]
}

extension InheritanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InheritanceTests = [
        ("testInheritance", testInheritance),
    ]
}

extension LexerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LexerTests = [
        ("testComment", testComment),
        ("testContentMixture", testContentMixture),
        ("testEmptyVariable", testEmptyVariable),
        ("testEscapeSequence", testEscapeSequence),
        ("testNewlines", testNewlines),
        ("testPerformance", testPerformance),
        ("testText", testText),
        ("testTokenizeIncorrectSyntaxWithoutCrashing", testTokenizeIncorrectSyntaxWithoutCrashing),
        ("testTokenWithoutSpaces", testTokenWithoutSpaces),
        ("testTrimSymbols", testTrimSymbols),
        ("testUnclosedBlock", testUnclosedBlock),
        ("testUnclosedTag", testUnclosedTag),
        ("testVariable", testVariable),
        ("testVariablesWithoutBeingGreedy", testVariablesWithoutBeingGreedy),
    ]
}

extension NodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NodeTests = [
        ("testRendering", testRendering),
        ("testTextNode", testTextNode),
        ("testVariableNode", testVariableNode),
    ]
}

extension NowNodeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NowNodeTests = [
        ("testParsing", testParsing),
        ("testRendering", testRendering),
    ]
}

extension StencilTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StencilTests = [
        ("testStencil", testStencil),
    ]
}

extension TemplateLoaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TemplateLoaderTests = [
        ("testDictionaryLoader", testDictionaryLoader),
        ("testFileSystemLoader", testFileSystemLoader),
    ]
}

extension TemplateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TemplateTests = [
        ("testTemplate", testTemplate),
    ]
}

extension TokenParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TokenParserTests = [
        ("testTokenParser", testTokenParser),
    ]
}

extension TokenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TokenTests = [
        ("testToken", testToken),
    ]
}

extension TrimBehaviorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TrimBehaviorTests = [
        ("testSmartTrimBehaviour", testSmartTrimBehaviour),
        ("testTrimSymbols", testTrimSymbols),
        ("testTrimSymbolsOverridingEnvironment", testTrimSymbolsOverridingEnvironment),
    ]
}

extension VariableTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__VariableTests = [
        ("testArray", testArray),
        ("testDictionary", testDictionary),
        ("testKVO", testKVO),
        ("testLiterals", testLiterals),
        ("testMultipleSubscripting", testMultipleSubscripting),
        ("testOptional", testOptional),
        ("testRangeVariable", testRangeVariable),
        ("testReflection", testReflection),
        ("testSubscripting", testSubscripting),
        ("testTuple", testTuple),
        ("testVariable", testVariable),
    ]
}

#if !os(macOS)
public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ContextTests.__allTests__ContextTests),
        testCase(EnvironmentBaseAndChildTemplateTests.__allTests__EnvironmentBaseAndChildTemplateTests),
        testCase(EnvironmentIncludeTemplateTests.__allTests__EnvironmentIncludeTemplateTests),
        testCase(EnvironmentTests.__allTests__EnvironmentTests),
        testCase(ExpressionsTests.__allTests__ExpressionsTests),
        testCase(FilterTagTests.__allTests__FilterTagTests),
        testCase(FilterTests.__allTests__FilterTests),
        testCase(ForNodeTests.__allTests__ForNodeTests),
        testCase(IfNodeTests.__allTests__IfNodeTests),
        testCase(IncludeTests.__allTests__IncludeTests),
        testCase(InheritanceTests.__allTests__InheritanceTests),
        testCase(LexerTests.__allTests__LexerTests),
        testCase(NodeTests.__allTests__NodeTests),
        testCase(NowNodeTests.__allTests__NowNodeTests),
        testCase(StencilTests.__allTests__StencilTests),
        testCase(TemplateLoaderTests.__allTests__TemplateLoaderTests),
        testCase(TemplateTests.__allTests__TemplateTests),
        testCase(TokenParserTests.__allTests__TokenParserTests),
        testCase(TokenTests.__allTests__TokenTests),
        testCase(TrimBehaviorTests.__allTests__TrimBehaviorTests),
        testCase(VariableTests.__allTests__VariableTests),
    ]
}
#endif
